config/routes.rb
Rails.application.routes.draw do
	root 'orders#index'
    resources :orders
    resources :menu_items
	

end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
	has_and_belongs_to_many :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_and_belongs_to_many :menu_items

	ORDERS = ['Brioche French Toast', 'Bircher Muesli', 'Scrambled Egg', 'Toast with honey or jam or marmite',
	'Fruit Salad and Yoghurt','Vegetarian Burger', 'Bacon & Egg Roll with coffee', 'BLT with coffee']
	DRINKS = ['Cappuccino', 'Americano', 'Latte', 'Espresso', 'Cortado', 'Flat White', 'Macchiato', 'Orange Juice']

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/menu_items_controller.rb
class Menu_itemsController < ApplicationController

	#to get comments to show up at each article, they should show up under "show"

	def create
		@order = Order.find(params[:order_id])
		@menu_item = @order.menu_items.create(menu_item_params)
		redirect_to order_path(@order)
	end

	def destroy
		@order = Order.find(params[:order_id])
		@menu_item = @order.menu_items.find(params[:id])
		@menu_item.delete
		redirect_to order_path(@order)
	end

	private
	def menu_item_params
		params.require(:menu_item).permit(:item)
	end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def index
		@orders = Order.all
	end

	def show
		@order = Order.find(params[:id])
		# @menu_items = @order.menu_items

	end

	def new
		@order = Order.new
	end

	def create
		@order = Order.new(order_params)

		if @order.save
			redirect_to @order
		else
			render 'new'
		end
	end

	def edit
		@order = Order.find params[:id]
	end

	def update

		@order = Order.find(params[:id])

		if @order.update(order_params)
			redirect_to @order
		else
			render 'edit'
		end
	end

	def destroy
		@order = Order.find params[:id]
		@order.destroy
		redirect_to orders_path
	end

	private
	def order_params
		params.require(:order).permit(:orderer, :drink, :dish, :comment)
	end

	# if menu item
	# 	menu_item.save
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Week2Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="knead-bg">

<div class="nav-header">
<%= image_tag 'knead.jpg', class: 'knead-logo' %>
</div>

<%= yield %>

</body>
</html>

app/views/menu_items/_form.html.erb
<%= form_for @order do |f| %>
	<div>
		<%= f.label :dish %>
		<%= f.collection_select :dish, Order::ORDERS, :to_s, :to_s,
			:include_blank => true
		%>
	</div>

	<div>
	<%= f.label :drink %>
			<%= f.collection_select :drink, Order::DRINKS, :to_s, :to_s,
			:include_blank => true
		%>
	</div>

		<div>
		<%= f.submit %>
	</div>

<% end %>

app/views/menu_items/index.html.erb
<h1>Full Menu</h1>
 <%= link_to 'New Order', new_order_path %>
 <%= link_to 'All Orders', orders_path %>

<table>
	<tr>
		<th>Item</th>
		<th>Price</th>
		<th colspan="5"></th>
	</tr>
	<% @menu.each do |item| %>
		<tr>
			<td><%= item.item %></td>
			<td><%= item.price %></td>
		</tr>
	<% end %>
</table>

app/views/orders/_form.html.erb
<%= form_for @order do |f| %>
	<div>
		<%= f.label "Your Name" %>
		<%= f.text_field :orderer %>
	</div>


	<div>
		<%= f.label "Specific instructions" %>
		<%= f.text_field :comment %>
	</div>

	<div>
		<%= f.submit %>
	</div>

<% end %>

app/views/orders/edit.html.erb
<h1>Edit order information</h1>
 
<%= render 'form' %>

<h2>Add an item:</h2>

</br>

<%= link_to 'Back to index', orders_path %>

app/views/orders/index.html.erb
<div class="wrapper">
	<div class="container center">
		<h1>All orders</h1>
		<div class="btn new-order">
		<%= link_to 'New order', new_order_path %>
		</div>
		<table class="centerTable">
			<tr>
				<th>Orderer</th>
				<th>Order</th>
				<th>Comments</th>
				<th colspan="2", col width = "380"></th>
			</tr>
			<% @orders.each do |order| %>
			<tr>
				<td><%= order.orderer %>  |</td>
				<td><%= order.dish %>, </td>
				<td><%= order.drink %></td>
				<td><%= order.comment %></td>
				<td class="btn btn-default"><%= link_to 'Show', order_path(order) %></td>
				<td class="btn btn-default"><%= link_to 'Edit', edit_order_path(order) %></td>
				<td class="btn btn-default"><%= link_to 'Delete', order_path(order),
					method: :delete,
					data: { confirm: 'Are you sure?' } %></td>
				</tr>
				<% end %>
			</table>
		</div>
	</div>

app/views/orders/new.html.erb
<h1> What would you like on this lovely morning? </h1>

<%= render 'form' %>
<%= render 'menu_items/form' %>


<%= link_to 'Back to Index', orders_path %> 

app/views/orders/show.html.erb
<h1><%= @order.orderer %>'s Order</h1>

	<h2>Menu items chosen</h2>
			<%= @order.dish %> </br>
			<%= @order.drink %>
	<h2>Specific Requests:</h2>
		<%= @order.comment %>
</br>
 
<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %> |
<%= link_to 'Delete', order_path, method: :delete %>